git checkout develop
git pull origin develop
git push origin develop

git branch -D master
git checkout -b master
npm run build

echo lunar.haus > CNAME
git add CNAME
git add index.html
git add -f ./dist
git commit -m "Autogenerated commit from build"
git push origin master --force

rm CNAME
git checkout -
